services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
  minio:
    image: minio/minio:RELEASE.2024-01-28T22-35-53Z
    container_name: minio
    volumes:
      - minio_data:/data
    env_file:
      - ./.env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  opensearch:
    build: 
      context: ./opensearch
      dockerfile: Dockerfile
    container_name: opensearch
    env_file:
      - ./.env
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

volumes:
  pgdata:
  minio_data:
  redis_data:
