# Generated by Django 6.0.6 on 2026-06-17 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_albumartist_album_artists_history_trackauthor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', through='core.AlbumArtist', to='core.artist'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('user', 'track', 'date')},
        ),
    ]
