# Generated by Django 6.0.6 on 2026-06-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_track_album_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album', verbose_name='Альбом'),
        ),
    ]
