# Generated by Django 6.0.6 on 2026-06-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='tracks'),
        ),
    ]
