# Generated by Django 6.0.6 on 2026-06-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_track_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
